name: Daily Email Summary

on:
  schedule:
    - cron: '0 13 * * *'  # Runs at 1 PM UTC daily

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures a full, fresh clone

      - name: Force fresh pull
        run: git fetch --prune --unshallow

      - name: Check Python version
        run: python --version

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Clear Python cache
        run: python -m pip cache purge

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv google-auth-oauthlib google-auth-httplib2 google-api-python-client google-cloud-aiplatform

      - name: Install Vertex AI SDK
        run: pip install google-cloud-aiplatform --upgrade

      - name: Run script
        env:
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python github_main.py
